---
abstract: 'Provides a set of Catalyst modules'
author:
  - 'cPanel <cpanel@cpan.org>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Cpanel-Catalyst
requires:
  Cache::FastMmap: 0
  Catalyst: 0
  Catalyst::ActionRole::ACL: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Controller::REST: 0
  Catalyst::Devel: 0
  Catalyst::Log::Log4perl: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::AutoCRUD: 0
  Catalyst::Plugin::Browser: 0
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::Cache::FastMmap: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::HashedCookies: 0
  Catalyst::Plugin::Redirect: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::UploadProgress: 0
  Catalyst::View::TT: 0
  DBIx::Class: 0
  DateTime::Format::Pg: 0
  FCGI: 0
  Log::Dispatch: 0
  Net::OpenSSH: 0
  Net::SFTP::Foreign: 0
  Net::Telnet: 0
  forks: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/CpanelInc/Task-Cpanel-Catalyst
version: 11.36.001
